**Numpy provides a high-performance multidimensional array object, and tools for working with these arrays.**

https://www.mathsisfun.com/


In [ ]:
# Check how many dimensions the arrays have
import numpy as np

# numpy arrays are stored in contiguous locations unlike lists
# they are implemented in c++

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(4, 3)
print(newarr)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Reshaping with unknown dimension
arr = np.array([1, 2, 3, 4,5,6])
newarr = arr.reshape(3,-1)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Flattening
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
# iterate through 3D array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# easier way
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# random int
from numpy import random

x = random.randint(100)
print(x)

66


In [ ]:
# random float
from numpy import random

x = random.rand()
print(x)

0.6993568658027133


In [ ]:
# random array
from numpy import random

x = random.randint(100, size=(9,9,9,9,9,9,9))
print(x)

Buffered data was truncated after reaching the output size limit.

In [ ]:
# Array math

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [ ]:
print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**Broadcasting - The ability of NumPy to treat arrays of different shapes during arithmetic operations.**

* Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v  # Add v to each row of x using broadcasting
#y=x*3
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# Slicing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
import numpy as np
# Indexing
# Create a new array from which we will select elements
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(x)

# Create an array of indices
a=np.arange(4)
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(x[a, b])  # Prints "[ 1  6  7 11]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


* accessing row by row using for loop - bad practice.
* Use vector operations instead.

* https://www.geeksforgeeks.org/vectorization-in-python/

* https://realpython.com/numpy-array-programming/